{ ... }:
{
  imports = [
    ./hyprland-desktop
    ./terminal/wezterm
    ./terminal/kitty
    ./terminal/fish
    ./terminal/nushell
    ./terminal/starship
    ./terminal/zoxide
    ./terminal/ripgrep
    ./terminal/fd
    ./terminal/fzf
    ./terminal/btop
    ./terminal/fastfetch
    ./terminal/neovim
    ./terminal/helix
    ./terminal/lean-highlighter
    ./terminal/yazi
    ./terminal/git
    ./terminal/jujutsu
    ./terminal/lazygit
    ./terminal/nix-tools
    ./programs/firefox
    ./programs/nixcord
    ./programs/spicetify
    ./programs/zathura
  ];
}
