{ ... }:
{
  imports = [
    ./theme
    ./desktops/hyprland
    ./ui/gtk
    ./ui/kvantum
    ./programs/kitty
    ./programs/fish
    ./programs/nushell
    ./programs/starship
    ./programs/zoxide
    ./programs/ripgrep
    ./programs/fd
    ./programs/fzf
    ./programs/btop
    ./programs/fastfetch
    ./programs/avizo
    ./programs/imv
    ./programs/mpv
    ./programs/neovim
    ./programs/helix
    ./programs/lean-highlighter
    ./programs/yazi
    ./programs/swappy
    ./programs/thunar
    ./programs/git
    ./programs/jujutsu
    ./programs/lazygit
    ./programs/nix-tools
    ./programs/code
    ./programs/glide
    ./programs/nixcord
    ./programs/dunst
    ./programs/rofi
    ./programs/spicetify
    ./programs/waybar
    ./programs/wpaperd
    ./programs/wlogout
    ./programs/zathura
  ];
}
