{ lib, theme }:
''
    [mgr]
    cwd = { fg = "${theme.hex "teal"}" }

    hovered         = { fg = "${theme.hex "base"}", bg = "${theme.hex "blue"}" }
    preview_hovered = { fg = "${theme.hex "base"}", bg = "${theme.hex "text"}" }

    find_keyword  = { fg = "${theme.hex "yellow"}", italic = true }
    find_position = { fg = "${theme.hex "pink"}", bg = "reset", italic = true }

    marker_copied   = { fg = "${theme.hex "green"}", bg = "${theme.hex "green"}" }
    marker_cut      = { fg = "${theme.hex "red"}", bg = "${theme.hex "red"}" }
    marker_marked   = { fg = "${theme.hex "teal"}", bg = "${theme.hex "teal"}" }
    marker_selected = { fg = "${theme.hex "blue"}", bg = "${theme.hex "blue"}" }

    count_copied   = { fg = "${theme.hex "base"}", bg = "${theme.hex "green"}" }
    count_cut      = { fg = "${theme.hex "base"}", bg = "${theme.hex "red"}" }
    count_selected = { fg = "${theme.hex "base"}", bg = "${theme.hex "blue"}" }

    border_symbol = "│"
    border_style  = { fg = "${theme.hex "overlay1"}" }

    syntect_theme = "./${theme.selection.family}-${theme.selection.flavor}.tmTheme"

    [tabs]
    active   = { fg = "${theme.hex "base"}", bg = "${theme.hex "text"}", bold = true }
    inactive = { fg = "${theme.hex "text"}", bg = "${theme.hex "surface1"}" }

    [mode]
    normal_main = { fg = "${theme.hex "base"}", bg = "${theme.hex "blue"}", bold = true }
    normal_alt  = { fg = "${theme.hex "blue"}", bg = "${theme.hex "surface0"}" }

    select_main = { fg = "${theme.hex "base"}", bg = "${theme.hex "green"}", bold = true }
    select_alt  = { fg = "${theme.hex "green"}", bg = "${theme.hex "surface0"}" }

    unset_main = { fg = "${theme.hex "base"}", bg = "${theme.hex "flamingo"}", bold = true }
    unset_alt  = { fg = "${theme.hex "flamingo"}", bg = "${theme.hex "surface0"}" }

    [status]
    sep_left  = { open = "", close = "" }
    sep_right = { open = "", close = "" }

    progress_label  = { fg = "#ffffff", bold = true }
    progress_normal = { fg = "${theme.hex "blue"}", bg = "${theme.hex "surface1"}" }
    progress_error  = { fg = "${theme.hex "red"}", bg = "${theme.hex "surface1"}" }

    perm_type  = { fg = "${theme.hex "blue"}" }
    perm_read  = { fg = "${theme.hex "yellow"}" }
    perm_write = { fg = "${theme.hex "red"}" }
    perm_exec  = { fg = "${theme.hex "green"}" }
    perm_sep   = { fg = "${theme.hex "overlay1"}" }

    [input]
    border   = { fg = "${theme.hex "blue"}" }
    title    = {}
    value    = {}
    selected = { reversed = true }

    [pick]
    border   = { fg = "${theme.hex "blue"}" }
    active   = { fg = "${theme.hex "pink"}" }
    inactive = {}

    [confirm]
    border  = { fg = "${theme.hex "blue"}" }
    title   = { fg = "${theme.hex "blue"}" }
    content = {}
    list    = {}
    btn_yes = { reversed = true }
    btn_no  = {}

    [cmp]
    border = { fg = "${theme.hex "blue"}" }

    [tasks]
    border  = { fg = "${theme.hex "blue"}" }
    title   = {}
    hovered = { underline = true }

    [which]
    mask            = { bg = "${theme.hex "surface0"}" }
    cand            = { fg = "${theme.hex "teal"}" }
    rest            = { fg = "${theme.hex "overlay2"}" }
    desc            = { fg = "${theme.hex "pink"}" }
    separator       = "  "
    separator_style = { fg = "${theme.hex "surface2"}" }

    [help]
    on      = { fg = "${theme.hex "teal"}" }
    run     = { fg = "${theme.hex "pink"}" }
    desc    = { fg = "${theme.hex "overlay2"}" }
    hovered = { bg = "${theme.hex "surface2"}", bold = true }
    footer  = { fg = "${theme.hex "text"}", bg = "${theme.hex "surface1"}" }

    [notify]
    title_info  = { fg = "${theme.hex "teal"}" }
    title_warn  = { fg = "${theme.hex "yellow"}" }
    title_error = { fg = "${theme.hex "red"}" }

[filetype]
rules = [
	# Media
	{ mime = "image/*", fg = "${theme.hex "teal"}" },
	{ mime = "{audio,video}/*", fg = "${theme.hex "yellow"}" },

	# Archives
	{ mime = "application/*zip", fg = "${theme.hex "pink"}" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "${theme.hex "pink"}" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "${theme.hex "green"}" },

	# Fallback
	{ name = "*", fg = "${theme.hex "text"}" },
	{ name = "*/", fg = "${theme.hex "blue"}" }
]

[spot]
border = { fg = "${theme.hex "blue"}" }
title  = { fg = "${theme.hex "blue"}" }
tbl_cell = { fg = "${theme.hex "blue"}", reversed = true }
tbl_col = { bold = true }

[icon]
files = [
  { name = "kritadisplayrc", text = "", fg = "${theme.hex "mauve"}" },
  { name = ".gtkrc-2.0", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "bspwmrc", text = "", fg = "${theme.hex "mantle"}" },
  { name = "webpack", text = "󰜫", fg = "${theme.hex "sapphire"}" },
  { name = "tsconfig.json", text = "", fg = "${theme.hex "sapphire"}" },
  { name = ".vimrc", text = "", fg = "${theme.hex "green"}" },
  { name = "gemfile$", text = "", fg = "${theme.hex "crust"}" },
  { name = "xmobarrc", text = "", fg = "${theme.hex "red"}" },
  { name = "avif", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "fp-info-cache", text = "", fg = "${theme.hex "rosewater"}" },
  { name = ".zshrc", text = "", fg = "${theme.hex "green"}" },
  { name = "robots.txt", text = "󰚩", fg = "${theme.hex "overlay0"}" },
  { name = "dockerfile", text = "󰡨", fg = "${theme.hex "blue"}" },
  { name = ".git-blame-ignore-revs", text = "", fg = "${theme.hex "peach"}" },
  { name = ".nvmrc", text = "", fg = "${theme.hex "green"}" },
  { name = "hyprpaper.conf", text = "", fg = "${theme.hex "teal"}" },
  { name = ".prettierignore", text = "", fg = "${theme.hex "blue"}" },
  { name = "rakefile", text = "", fg = "${theme.hex "crust"}" },
  { name = "code_of_conduct", text = "", fg = "${theme.hex "red"}" },
  { name = "cmakelists.txt", text = "", fg = "${theme.hex "text"}" },
  { name = ".env", text = "", fg = "${theme.hex "yellow"}" },
  { name = "copying.lesser", text = "", fg = "${theme.hex "yellow"}" },
  { name = "readme", text = "󰂺", fg = "${theme.hex "rosewater"}" },
  { name = "settings.gradle", text = "", fg = "${theme.hex "surface2"}" },
  { name = "gruntfile.coffee", text = "", fg = "${theme.hex "peach"}" },
  { name = ".eslintignore", text = "", fg = "${theme.hex "surface1"}" },
  { name = "kalgebrarc", text = "", fg = "${theme.hex "blue"}" },
  { name = "kdenliverc", text = "", fg = "${theme.hex "blue"}" },
  { name = ".prettierrc.cjs", text = "", fg = "${theme.hex "blue"}" },
  { name = "cantorrc", text = "", fg = "${theme.hex "blue"}" },
  { name = "rmd", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "vagrantfile$", text = "", fg = "${theme.hex "overlay0"}" },
  { name = ".Xauthority", text = "", fg = "${theme.hex "peach"}" },
  { name = "prettier.config.ts", text = "", fg = "${theme.hex "blue"}" },
  { name = "node_modules", text = "", fg = "${theme.hex "red"}" },
  { name = ".prettierrc.toml", text = "", fg = "${theme.hex "blue"}" },
  { name = "build.zig.zon", text = "", fg = "${theme.hex "peach"}" },
  { name = ".ds_store", text = "", fg = "${theme.hex "surface1"}" },
  { name = "PKGBUILD", text = "", fg = "${theme.hex "blue"}" },
  { name = ".prettierrc", text = "", fg = "${theme.hex "blue"}" },
  { name = ".bash_profile", text = "", fg = "${theme.hex "green"}" },
  { name = ".npmignore", text = "", fg = "${theme.hex "red"}" },
  { name = ".mailmap", text = "󰊢", fg = "${theme.hex "peach"}" },
  { name = ".codespellrc", text = "󰓆", fg = "${theme.hex "green"}" },
  { name = "svelte.config.js", text = "", fg = "${theme.hex "peach"}" },
  { name = "eslint.config.ts", text = "", fg = "${theme.hex "surface1"}" },
  { name = "config", text = "", fg = "${theme.hex "overlay1"}" },
  { name = ".gitlab-ci.yml", text = "", fg = "${theme.hex "red"}" },
  { name = ".gitconfig", text = "", fg = "${theme.hex "peach"}" },
  { name = "_gvimrc", text = "", fg = "${theme.hex "green"}" },
  { name = ".xinitrc", text = "", fg = "${theme.hex "peach"}" },
  { name = "checkhealth", text = "󰓙", fg = "${theme.hex "blue"}" },
  { name = "sxhkdrc", text = "", fg = "${theme.hex "mantle"}" },
  { name = ".bashrc", text = "", fg = "${theme.hex "green"}" },
  { name = "tailwind.config.mjs", text = "󱏿", fg = "${theme.hex "sapphire"}" },
  { name = "ext_typoscript_setup.txt", text = "", fg = "${theme.hex "peach"}" },
  { name = "commitlint.config.ts", text = "󰜘", fg = "${theme.hex "teal"}" },
  { name = "py.typed", text = "", fg = "${theme.hex "yellow"}" },
  { name = ".nanorc", text = "", fg = "${theme.hex "base"}" },
  { name = "commit_editmsg", text = "", fg = "${theme.hex "peach"}" },
  { name = ".luaurc", text = "", fg = "${theme.hex "blue"}" },
  { name = "fp-lib-table", text = "", fg = "${theme.hex "rosewater"}" },
  { name = ".editorconfig", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "justfile", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "kdeglobals", text = "", fg = "${theme.hex "blue"}" },
  { name = "license.md", text = "", fg = "${theme.hex "yellow"}" },
  { name = ".clang-format", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "docker-compose.yaml", text = "󰡨", fg = "${theme.hex "blue"}" },
  { name = "copying", text = "", fg = "${theme.hex "yellow"}" },
  { name = "go.mod", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "lxqt.conf", text = "", fg = "${theme.hex "blue"}" },
  { name = "brewfile", text = "", fg = "${theme.hex "crust"}" },
  { name = "gulpfile.coffee", text = "", fg = "${theme.hex "red"}" },
  { name = ".dockerignore", text = "󰡨", fg = "${theme.hex "blue"}" },
  { name = ".settings.json", text = "", fg = "${theme.hex "surface2"}" },
  { name = "tailwind.config.js", text = "󱏿", fg = "${theme.hex "sapphire"}" },
  { name = ".clang-tidy", text = "", fg = "${theme.hex "overlay1"}" },
  { name = ".gvimrc", text = "", fg = "${theme.hex "green"}" },
  { name = "nuxt.config.cjs", text = "󱄆", fg = "${theme.hex "teal"}" },
  { name = "xsettingsd.conf", text = "", fg = "${theme.hex "peach"}" },
  { name = "nuxt.config.js", text = "󱄆", fg = "${theme.hex "teal"}" },
  { name = "eslint.config.cjs", text = "", fg = "${theme.hex "surface1"}" },
  { name = "sym-lib-table", text = "", fg = "${theme.hex "rosewater"}" },
  { name = ".condarc", text = "", fg = "${theme.hex "green"}" },
  { name = "xmonad.hs", text = "", fg = "${theme.hex "red"}" },
  { name = "tmux.conf", text = "", fg = "${theme.hex "green"}" },
  { name = "xmobarrc.hs", text = "", fg = "${theme.hex "red"}" },
  { name = ".prettierrc.yaml", text = "", fg = "${theme.hex "blue"}" },
  { name = ".pre-commit-config.yaml", text = "󰛢", fg = "${theme.hex "yellow"}" },
  { name = "i3blocks.conf", text = "", fg = "${theme.hex "text"}" },
  { name = "xorg.conf", text = "", fg = "${theme.hex "peach"}" },
  { name = ".zshenv", text = "", fg = "${theme.hex "green"}" },
  { name = "vlcrc", text = "󰕼", fg = "${theme.hex "peach"}" },
  { name = "license", text = "", fg = "${theme.hex "yellow"}" },
  { name = "unlicense", text = "", fg = "${theme.hex "yellow"}" },
  { name = "tmux.conf.local", text = "", fg = "${theme.hex "green"}" },
  { name = ".SRCINFO", text = "󰣇", fg = "${theme.hex "blue"}" },
  { name = "tailwind.config.ts", text = "󱏿", fg = "${theme.hex "sapphire"}" },
  { name = "security.md", text = "󰒃", fg = "${theme.hex "subtext1"}" },
  { name = "security", text = "󰒃", fg = "${theme.hex "subtext1"}" },
  { name = ".eslintrc", text = "", fg = "${theme.hex "surface1"}" },
  { name = "gradle.properties", text = "", fg = "${theme.hex "surface2"}" },
  { name = "code_of_conduct.md", text = "", fg = "${theme.hex "red"}" },
  { name = "PrusaSlicerGcodeViewer.ini", text = "", fg = "${theme.hex "peach"}" },
  { name = "PrusaSlicer.ini", text = "", fg = "${theme.hex "peach"}" },
  { name = "procfile", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "mpv.conf", text = "", fg = "${theme.hex "base"}" },
  { name = ".prettierrc.json5", text = "", fg = "${theme.hex "blue"}" },
  { name = "i3status.conf", text = "", fg = "${theme.hex "text"}" },
  { name = "prettier.config.mjs", text = "", fg = "${theme.hex "blue"}" },
  { name = ".pylintrc", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "prettier.config.cjs", text = "", fg = "${theme.hex "blue"}" },
  { name = ".luacheckrc", text = "", fg = "${theme.hex "blue"}" },
  { name = "containerfile", text = "󰡨", fg = "${theme.hex "blue"}" },
  { name = "eslint.config.mjs", text = "", fg = "${theme.hex "surface1"}" },
  { name = "gruntfile.js", text = "", fg = "${theme.hex "peach"}" },
  { name = "bun.lockb", text = "", fg = "${theme.hex "rosewater"}" },
  { name = ".gitattributes", text = "", fg = "${theme.hex "peach"}" },
  { name = "gruntfile.ts", text = "", fg = "${theme.hex "peach"}" },
  { name = "pom.xml", text = "", fg = "${theme.hex "surface0"}" },
  { name = "favicon.ico", text = "", fg = "${theme.hex "yellow"}" },
  { name = "package-lock.json", text = "", fg = "${theme.hex "surface0"}" },
  { name = "build", text = "", fg = "${theme.hex "green"}" },
  { name = "package.json", text = "", fg = "${theme.hex "red"}" },
  { name = "nuxt.config.ts", text = "󱄆", fg = "${theme.hex "teal"}" },
  { name = "nuxt.config.mjs", text = "󱄆", fg = "${theme.hex "teal"}" },
  { name = "mix.lock", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "makefile", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "gulpfile.js", text = "", fg = "${theme.hex "red"}" },
  { name = "lxde-rc.xml", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "kritarc", text = "", fg = "${theme.hex "mauve"}" },
  { name = "gtkrc", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "ionic.config.json", text = "", fg = "${theme.hex "blue"}" },
  { name = ".prettierrc.mjs", text = "", fg = "${theme.hex "blue"}" },
  { name = ".prettierrc.yml", text = "", fg = "${theme.hex "blue"}" },
  { name = ".npmrc", text = "", fg = "${theme.hex "red"}" },
  { name = "weston.ini", text = "", fg = "${theme.hex "yellow"}" },
  { name = "gulpfile.babel.js", text = "", fg = "${theme.hex "red"}" },
  { name = "i18n.config.ts", text = "󰗊", fg = "${theme.hex "overlay1"}" },
  { name = "commitlint.config.js", text = "󰜘", fg = "${theme.hex "teal"}" },
  { name = ".gitmodules", text = "", fg = "${theme.hex "peach"}" },
  { name = "gradle-wrapper.properties", text = "", fg = "${theme.hex "surface2"}" },
  { name = "hypridle.conf", text = "", fg = "${theme.hex "teal"}" },
  { name = "vercel.json", text = "▲", fg = "${theme.hex "rosewater"}" },
  { name = "hyprlock.conf", text = "", fg = "${theme.hex "teal"}" },
  { name = "go.sum", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "kdenlive-layoutsrc", text = "", fg = "${theme.hex "blue"}" },
  { name = "gruntfile.babel.js", text = "", fg = "${theme.hex "peach"}" },
  { name = "compose.yml", text = "󰡨", fg = "${theme.hex "blue"}" },
  { name = "i18n.config.js", text = "󰗊", fg = "${theme.hex "overlay1"}" },
  { name = "readme.md", text = "󰂺", fg = "${theme.hex "rosewater"}" },
  { name = "gradlew", text = "", fg = "${theme.hex "surface2"}" },
  { name = "go.work", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "gulpfile.ts", text = "", fg = "${theme.hex "red"}" },
  { name = "gnumakefile", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "FreeCAD.conf", text = "", fg = "${theme.hex "red"}" },
  { name = "compose.yaml", text = "󰡨", fg = "${theme.hex "blue"}" },
  { name = "eslint.config.js", text = "", fg = "${theme.hex "surface1"}" },
  { name = "hyprland.conf", text = "", fg = "${theme.hex "teal"}" },
  { name = "docker-compose.yml", text = "󰡨", fg = "${theme.hex "blue"}" },
  { name = "groovy", text = "", fg = "${theme.hex "surface2"}" },
  { name = "QtProject.conf", text = "", fg = "${theme.hex "green"}" },
  { name = "platformio.ini", text = "", fg = "${theme.hex "peach"}" },
  { name = "build.gradle", text = "", fg = "${theme.hex "surface2"}" },
  { name = ".nuxtrc", text = "󱄆", fg = "${theme.hex "teal"}" },
  { name = "_vimrc", text = "", fg = "${theme.hex "green"}" },
  { name = ".zprofile", text = "", fg = "${theme.hex "green"}" },
  { name = ".xsession", text = "", fg = "${theme.hex "peach"}" },
  { name = "prettier.config.js", text = "", fg = "${theme.hex "blue"}" },
  { name = ".babelrc", text = "", fg = "${theme.hex "yellow"}" },
  { name = "workspace", text = "", fg = "${theme.hex "green"}" },
  { name = ".prettierrc.json", text = "", fg = "${theme.hex "blue"}" },
  { name = ".prettierrc.js", text = "", fg = "${theme.hex "blue"}" },
  { name = ".Xresources", text = "", fg = "${theme.hex "peach"}" },
  { name = ".gitignore", text = "", fg = "${theme.hex "peach"}" },
  { name = ".justfile", text = "", fg = "${theme.hex "overlay1"}" },
]
exts = [
  { name = "otf", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "import", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "krz", text = "", fg = "${theme.hex "mauve"}" },
  { name = "adb", text = "", fg = "${theme.hex "teal"}" },
  { name = "ttf", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "webpack", text = "󰜫", fg = "${theme.hex "sapphire"}" },
  { name = "dart", text = "", fg = "${theme.hex "surface2"}" },
  { name = "vsh", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "doc", text = "󰈬", fg = "${theme.hex "surface2"}" },
  { name = "zsh", text = "", fg = "${theme.hex "green"}" },
  { name = "ex", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "hx", text = "", fg = "${theme.hex "peach"}" },
  { name = "fodt", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "mojo", text = "", fg = "${theme.hex "peach"}" },
  { name = "templ", text = "", fg = "${theme.hex "yellow"}" },
  { name = "nix", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "cshtml", text = "󱦗", fg = "${theme.hex "surface1"}" },
  { name = "fish", text = "", fg = "${theme.hex "surface2"}" },
  { name = "ply", text = "󰆧", fg = "${theme.hex "overlay1"}" },
  { name = "sldprt", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "gemspec", text = "", fg = "${theme.hex "crust"}" },
  { name = "mjs", text = "", fg = "${theme.hex "yellow"}" },
  { name = "csh", text = "", fg = "${theme.hex "surface2"}" },
  { name = "cmake", text = "", fg = "${theme.hex "text"}" },
  { name = "fodp", text = "", fg = "${theme.hex "peach"}" },
  { name = "vi", text = "", fg = "${theme.hex "yellow"}" },
  { name = "msf", text = "", fg = "${theme.hex "blue"}" },
  { name = "blp", text = "󰺾", fg = "${theme.hex "blue"}" },
  { name = "less", text = "", fg = "${theme.hex "surface1"}" },
  { name = "sh", text = "", fg = "${theme.hex "surface2"}" },
  { name = "odg", text = "", fg = "${theme.hex "yellow"}" },
  { name = "mint", text = "󰌪", fg = "${theme.hex "green"}" },
  { name = "dll", text = "", fg = "${theme.hex "crust"}" },
  { name = "odf", text = "", fg = "${theme.hex "red"}" },
  { name = "sqlite3", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "Dockerfile", text = "󰡨", fg = "${theme.hex "blue"}" },
  { name = "ksh", text = "", fg = "${theme.hex "surface2"}" },
  { name = "rmd", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "wv", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "xml", text = "󰗀", fg = "${theme.hex "peach"}" },
  { name = "markdown", text = "", fg = "${theme.hex "text"}" },
  { name = "qml", text = "", fg = "${theme.hex "green"}" },
  { name = "3gp", text = "", fg = "${theme.hex "peach"}" },
  { name = "pxi", text = "", fg = "${theme.hex "blue"}" },
  { name = "flac", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "gpr", text = "", fg = "${theme.hex "mauve"}" },
  { name = "huff", text = "󰡘", fg = "${theme.hex "surface1"}" },
  { name = "json", text = "", fg = "${theme.hex "yellow"}" },
  { name = "gv", text = "󱁉", fg = "${theme.hex "surface2"}" },
  { name = "bmp", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "lock", text = "", fg = "${theme.hex "subtext1"}" },
  { name = "sha384", text = "󰕥", fg = "${theme.hex "overlay1"}" },
  { name = "cobol", text = "⚙", fg = "${theme.hex "surface2"}" },
  { name = "cob", text = "⚙", fg = "${theme.hex "surface2"}" },
  { name = "java", text = "", fg = "${theme.hex "red"}" },
  { name = "cjs", text = "", fg = "${theme.hex "yellow"}" },
  { name = "qm", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "ebuild", text = "", fg = "${theme.hex "surface1"}" },
  { name = "mustache", text = "", fg = "${theme.hex "peach"}" },
  { name = "terminal", text = "", fg = "${theme.hex "green"}" },
  { name = "ejs", text = "", fg = "${theme.hex "yellow"}" },
  { name = "brep", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "rar", text = "", fg = "${theme.hex "yellow"}" },
  { name = "gradle", text = "", fg = "${theme.hex "surface2"}" },
  { name = "gnumakefile", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "applescript", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "elm", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "ebook", text = "", fg = "${theme.hex "peach"}" },
  { name = "kra", text = "", fg = "${theme.hex "mauve"}" },
  { name = "tf", text = "", fg = "${theme.hex "surface2"}" },
  { name = "xls", text = "󰈛", fg = "${theme.hex "surface2"}" },
  { name = "fnl", text = "", fg = "${theme.hex "yellow"}" },
  { name = "kdbx", text = "", fg = "${theme.hex "green"}" },
  { name = "kicad_pcb", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "cfg", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "ape", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "org", text = "", fg = "${theme.hex "teal"}" },
  { name = "yml", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "swift", text = "", fg = "${theme.hex "peach"}" },
  { name = "eln", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "sol", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "awk", text = "", fg = "${theme.hex "surface2"}" },
  { name = "7z", text = "", fg = "${theme.hex "yellow"}" },
  { name = "apl", text = "⍝", fg = "${theme.hex "peach"}" },
  { name = "epp", text = "", fg = "${theme.hex "peach"}" },
  { name = "app", text = "", fg = "${theme.hex "surface1"}" },
  { name = "dot", text = "󱁉", fg = "${theme.hex "surface2"}" },
  { name = "kpp", text = "", fg = "${theme.hex "mauve"}" },
  { name = "eot", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "hpp", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "spec.tsx", text = "", fg = "${theme.hex "surface2"}" },
  { name = "hurl", text = "", fg = "${theme.hex "red"}" },
  { name = "cxxm", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "c", text = "", fg = "${theme.hex "blue"}" },
  { name = "fcmacro", text = "", fg = "${theme.hex "red"}" },
  { name = "sass", text = "", fg = "${theme.hex "red"}" },
  { name = "yaml", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "xz", text = "", fg = "${theme.hex "yellow"}" },
  { name = "material", text = "󰔉", fg = "${theme.hex "overlay0"}" },
  { name = "json5", text = "", fg = "${theme.hex "yellow"}" },
  { name = "signature", text = "λ", fg = "${theme.hex "peach"}" },
  { name = "3mf", text = "󰆧", fg = "${theme.hex "overlay1"}" },
  { name = "jpg", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "xpi", text = "", fg = "${theme.hex "peach"}" },
  { name = "fcmat", text = "", fg = "${theme.hex "red"}" },
  { name = "pot", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "bin", text = "", fg = "${theme.hex "surface1"}" },
  { name = "xlsx", text = "󰈛", fg = "${theme.hex "surface2"}" },
  { name = "aac", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "kicad_sym", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "xcstrings", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "lff", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "xcf", text = "", fg = "${theme.hex "surface2"}" },
  { name = "azcli", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "license", text = "", fg = "${theme.hex "yellow"}" },
  { name = "jsonc", text = "", fg = "${theme.hex "yellow"}" },
  { name = "xaml", text = "󰙳", fg = "${theme.hex "surface1"}" },
  { name = "md5", text = "󰕥", fg = "${theme.hex "overlay1"}" },
  { name = "xm", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "sln", text = "", fg = "${theme.hex "surface2"}" },
  { name = "jl", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "ml", text = "", fg = "${theme.hex "peach"}" },
  { name = "http", text = "", fg = "${theme.hex "blue"}" },
  { name = "x", text = "", fg = "${theme.hex "blue"}" },
  { name = "wvc", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "wrz", text = "󰆧", fg = "${theme.hex "overlay1"}" },
  { name = "csproj", text = "󰪮", fg = "${theme.hex "surface1"}" },
  { name = "wrl", text = "󰆧", fg = "${theme.hex "overlay1"}" },
  { name = "wma", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "woff2", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "woff", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "tscn", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "webmanifest", text = "", fg = "${theme.hex "yellow"}" },
  { name = "webm", text = "", fg = "${theme.hex "peach"}" },
  { name = "fcbak", text = "", fg = "${theme.hex "red"}" },
  { name = "log", text = "󰌱", fg = "${theme.hex "text"}" },
  { name = "wav", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "wasm", text = "", fg = "${theme.hex "surface2"}" },
  { name = "styl", text = "", fg = "${theme.hex "green"}" },
  { name = "gif", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "resi", text = "", fg = "${theme.hex "red"}" },
  { name = "aiff", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "sha256", text = "󰕥", fg = "${theme.hex "overlay1"}" },
  { name = "igs", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "vsix", text = "", fg = "${theme.hex "surface2"}" },
  { name = "vim", text = "", fg = "${theme.hex "green"}" },
  { name = "diff", text = "", fg = "${theme.hex "surface1"}" },
  { name = "drl", text = "", fg = "${theme.hex "maroon"}" },
  { name = "erl", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "vhdl", text = "󰍛", fg = "${theme.hex "green"}" },
  { name = "🔥", text = "", fg = "${theme.hex "peach"}" },
  { name = "hrl", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "fsi", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "mm", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "bz", text = "", fg = "${theme.hex "yellow"}" },
  { name = "vh", text = "󰍛", fg = "${theme.hex "green"}" },
  { name = "kdb", text = "", fg = "${theme.hex "green"}" },
  { name = "gz", text = "", fg = "${theme.hex "yellow"}" },
  { name = "cpp", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "ui", text = "", fg = "${theme.hex "surface2"}" },
  { name = "txt", text = "󰈙", fg = "${theme.hex "green"}" },
  { name = "spec.ts", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "ccm", text = "", fg = "${theme.hex "red"}" },
  { name = "typoscript", text = "", fg = "${theme.hex "peach"}" },
  { name = "typ", text = "", fg = "${theme.hex "teal"}" },
  { name = "txz", text = "", fg = "${theme.hex "yellow"}" },
  { name = "test.ts", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "tsx", text = "", fg = "${theme.hex "surface2"}" },
  { name = "mk", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "webp", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "opus", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "bicep", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "ts", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "tres", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "torrent", text = "", fg = "${theme.hex "teal"}" },
  { name = "cxx", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "iso", text = "", fg = "${theme.hex "flamingo"}" },
  { name = "ixx", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "hxx", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "gql", text = "", fg = "${theme.hex "red"}" },
  { name = "tmux", text = "", fg = "${theme.hex "green"}" },
  { name = "ini", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "m3u8", text = "󰲹", fg = "${theme.hex "red"}" },
  { name = "image", text = "", fg = "${theme.hex "flamingo"}" },
  { name = "tfvars", text = "", fg = "${theme.hex "surface2"}" },
  { name = "tex", text = "", fg = "${theme.hex "surface1"}" },
  { name = "cbl", text = "⚙", fg = "${theme.hex "surface2"}" },
  { name = "flc", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "elc", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "test.tsx", text = "", fg = "${theme.hex "surface2"}" },
  { name = "twig", text = "", fg = "${theme.hex "green"}" },
  { name = "sql", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "test.jsx", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "htm", text = "", fg = "${theme.hex "peach"}" },
  { name = "gcode", text = "󰐫", fg = "${theme.hex "overlay0"}" },
  { name = "test.js", text = "", fg = "${theme.hex "yellow"}" },
  { name = "ino", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "tcl", text = "󰛓", fg = "${theme.hex "surface2"}" },
  { name = "cljs", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "tsconfig", text = "", fg = "${theme.hex "peach"}" },
  { name = "img", text = "", fg = "${theme.hex "flamingo"}" },
  { name = "t", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "fcstd1", text = "", fg = "${theme.hex "red"}" },
  { name = "out", text = "", fg = "${theme.hex "surface1"}" },
  { name = "jsx", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "bash", text = "", fg = "${theme.hex "green"}" },
  { name = "edn", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "rss", text = "", fg = "${theme.hex "peach"}" },
  { name = "flf", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "cache", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "sbt", text = "", fg = "${theme.hex "red"}" },
  { name = "cppm", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "svelte", text = "", fg = "${theme.hex "peach"}" },
  { name = "mo", text = "∞", fg = "${theme.hex "overlay1"}" },
  { name = "sv", text = "󰍛", fg = "${theme.hex "green"}" },
  { name = "ko", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "suo", text = "", fg = "${theme.hex "surface2"}" },
  { name = "sldasm", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "icalendar", text = "", fg = "${theme.hex "surface0"}" },
  { name = "go", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "sublime", text = "", fg = "${theme.hex "peach"}" },
  { name = "stl", text = "󰆧", fg = "${theme.hex "overlay1"}" },
  { name = "mobi", text = "", fg = "${theme.hex "peach"}" },
  { name = "graphql", text = "", fg = "${theme.hex "red"}" },
  { name = "m3u", text = "󰲹", fg = "${theme.hex "red"}" },
  { name = "cpy", text = "⚙", fg = "${theme.hex "surface2"}" },
  { name = "kdenlive", text = "", fg = "${theme.hex "blue"}" },
  { name = "pyo", text = "", fg = "${theme.hex "yellow"}" },
  { name = "po", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "scala", text = "", fg = "${theme.hex "red"}" },
  { name = "exs", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "odp", text = "", fg = "${theme.hex "peach"}" },
  { name = "dump", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "stp", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "step", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "ste", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "aif", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "strings", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "cp", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "fsscript", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "mli", text = "", fg = "${theme.hex "peach"}" },
  { name = "bak", text = "󰁯", fg = "${theme.hex "overlay1"}" },
  { name = "ssa", text = "󰨖", fg = "${theme.hex "yellow"}" },
  { name = "toml", text = "", fg = "${theme.hex "red"}" },
  { name = "makefile", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "php", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "zst", text = "", fg = "${theme.hex "yellow"}" },
  { name = "spec.jsx", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "kbx", text = "󰯄", fg = "${theme.hex "overlay0"}" },
  { name = "fbx", text = "󰆧", fg = "${theme.hex "overlay1"}" },
  { name = "blend", text = "󰂫", fg = "${theme.hex "peach"}" },
  { name = "ifc", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "spec.js", text = "", fg = "${theme.hex "yellow"}" },
  { name = "so", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "desktop", text = "", fg = "${theme.hex "surface1"}" },
  { name = "sml", text = "λ", fg = "${theme.hex "peach"}" },
  { name = "slvs", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "pp", text = "", fg = "${theme.hex "peach"}" },
  { name = "ps1", text = "󰨊", fg = "${theme.hex "overlay0"}" },
  { name = "dropbox", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "kicad_mod", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "bat", text = "", fg = "${theme.hex "green"}" },
  { name = "slim", text = "", fg = "${theme.hex "peach"}" },
  { name = "skp", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "css", text = "", fg = "${theme.hex "blue"}" },
  { name = "xul", text = "", fg = "${theme.hex "peach"}" },
  { name = "ige", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "glb", text = "", fg = "${theme.hex "peach"}" },
  { name = "ppt", text = "󰈧", fg = "${theme.hex "red"}" },
  { name = "sha512", text = "󰕥", fg = "${theme.hex "overlay1"}" },
  { name = "ics", text = "", fg = "${theme.hex "surface0"}" },
  { name = "mdx", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "sha1", text = "󰕥", fg = "${theme.hex "overlay1"}" },
  { name = "f3d", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "ass", text = "󰨖", fg = "${theme.hex "yellow"}" },
  { name = "godot", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "ifb", text = "", fg = "${theme.hex "surface0"}" },
  { name = "cson", text = "", fg = "${theme.hex "yellow"}" },
  { name = "lib", text = "", fg = "${theme.hex "crust"}" },
  { name = "luac", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "heex", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "scm", text = "󰘧", fg = "${theme.hex "rosewater"}" },
  { name = "psd1", text = "󰨊", fg = "${theme.hex "overlay0"}" },
  { name = "sc", text = "", fg = "${theme.hex "red"}" },
  { name = "scad", text = "", fg = "${theme.hex "yellow"}" },
  { name = "kts", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "svh", text = "󰍛", fg = "${theme.hex "green"}" },
  { name = "mts", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "nfo", text = "", fg = "${theme.hex "yellow"}" },
  { name = "pck", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "rproj", text = "󰗆", fg = "${theme.hex "green"}" },
  { name = "rlib", text = "", fg = "${theme.hex "peach"}" },
  { name = "cljd", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "ods", text = "", fg = "${theme.hex "green"}" },
  { name = "res", text = "", fg = "${theme.hex "red"}" },
  { name = "apk", text = "", fg = "${theme.hex "green"}" },
  { name = "haml", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "d.ts", text = "", fg = "${theme.hex "peach"}" },
  { name = "razor", text = "󱦘", fg = "${theme.hex "surface1"}" },
  { name = "rake", text = "", fg = "${theme.hex "crust"}" },
  { name = "patch", text = "", fg = "${theme.hex "surface1"}" },
  { name = "cuh", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "d", text = "", fg = "${theme.hex "red"}" },
  { name = "query", text = "", fg = "${theme.hex "green"}" },
  { name = "psb", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "nu", text = ">", fg = "${theme.hex "green"}" },
  { name = "mov", text = "", fg = "${theme.hex "peach"}" },
  { name = "lrc", text = "󰨖", fg = "${theme.hex "yellow"}" },
  { name = "pyx", text = "", fg = "${theme.hex "blue"}" },
  { name = "pyw", text = "", fg = "${theme.hex "blue"}" },
  { name = "cu", text = "", fg = "${theme.hex "green"}" },
  { name = "bazel", text = "", fg = "${theme.hex "green"}" },
  { name = "obj", text = "󰆧", fg = "${theme.hex "overlay1"}" },
  { name = "pyi", text = "", fg = "${theme.hex "yellow"}" },
  { name = "pyd", text = "", fg = "${theme.hex "yellow"}" },
  { name = "exe", text = "", fg = "${theme.hex "surface1"}" },
  { name = "pyc", text = "", fg = "${theme.hex "yellow"}" },
  { name = "fctb", text = "", fg = "${theme.hex "red"}" },
  { name = "part", text = "", fg = "${theme.hex "teal"}" },
  { name = "blade.php", text = "", fg = "${theme.hex "red"}" },
  { name = "git", text = "", fg = "${theme.hex "peach"}" },
  { name = "psd", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "qss", text = "", fg = "${theme.hex "green"}" },
  { name = "csv", text = "", fg = "${theme.hex "green"}" },
  { name = "psm1", text = "󰨊", fg = "${theme.hex "overlay0"}" },
  { name = "dconf", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "config.ru", text = "", fg = "${theme.hex "crust"}" },
  { name = "prisma", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "conf", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "clj", text = "", fg = "${theme.hex "green"}" },
  { name = "o", text = "", fg = "${theme.hex "surface1"}" },
  { name = "mp4", text = "", fg = "${theme.hex "peach"}" },
  { name = "cc", text = "", fg = "${theme.hex "red"}" },
  { name = "kicad_prl", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "bz3", text = "", fg = "${theme.hex "yellow"}" },
  { name = "asc", text = "󰦝", fg = "${theme.hex "surface2"}" },
  { name = "png", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "android", text = "", fg = "${theme.hex "green"}" },
  { name = "pm", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "h", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "pls", text = "󰲹", fg = "${theme.hex "red"}" },
  { name = "ipynb", text = "", fg = "${theme.hex "peach"}" },
  { name = "pl", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "ads", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "sqlite", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "pdf", text = "", fg = "${theme.hex "red"}" },
  { name = "pcm", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "ico", text = "", fg = "${theme.hex "yellow"}" },
  { name = "a", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "R", text = "󰟔", fg = "${theme.hex "surface2"}" },
  { name = "ogg", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "pxd", text = "", fg = "${theme.hex "blue"}" },
  { name = "kdenlivetitle", text = "", fg = "${theme.hex "blue"}" },
  { name = "jxl", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "nswag", text = "", fg = "${theme.hex "green"}" },
  { name = "nim", text = "", fg = "${theme.hex "yellow"}" },
  { name = "bqn", text = "⎉", fg = "${theme.hex "surface2"}" },
  { name = "cts", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "fcparam", text = "", fg = "${theme.hex "red"}" },
  { name = "rs", text = "", fg = "${theme.hex "peach"}" },
  { name = "mpp", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "fdmdownload", text = "", fg = "${theme.hex "teal"}" },
  { name = "pptx", text = "󰈧", fg = "${theme.hex "red"}" },
  { name = "jpeg", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "bib", text = "󱉟", fg = "${theme.hex "yellow"}" },
  { name = "vhd", text = "󰍛", fg = "${theme.hex "green"}" },
  { name = "m", text = "", fg = "${theme.hex "blue"}" },
  { name = "js", text = "", fg = "${theme.hex "yellow"}" },
  { name = "eex", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "tbc", text = "󰛓", fg = "${theme.hex "surface2"}" },
  { name = "astro", text = "", fg = "${theme.hex "red"}" },
  { name = "sha224", text = "󰕥", fg = "${theme.hex "overlay1"}" },
  { name = "xcplayground", text = "", fg = "${theme.hex "peach"}" },
  { name = "el", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "m4v", text = "", fg = "${theme.hex "peach"}" },
  { name = "m4a", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "cs", text = "󰌛", fg = "${theme.hex "green"}" },
  { name = "hs", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "tgz", text = "", fg = "${theme.hex "yellow"}" },
  { name = "fs", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "luau", text = "", fg = "${theme.hex "blue"}" },
  { name = "dxf", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "download", text = "", fg = "${theme.hex "teal"}" },
  { name = "cast", text = "", fg = "${theme.hex "peach"}" },
  { name = "qrc", text = "", fg = "${theme.hex "green"}" },
  { name = "lua", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "lhs", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "md", text = "", fg = "${theme.hex "text"}" },
  { name = "leex", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "ai", text = "", fg = "${theme.hex "yellow"}" },
  { name = "lck", text = "", fg = "${theme.hex "subtext1"}" },
  { name = "kt", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "bicepparam", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "hex", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "zig", text = "", fg = "${theme.hex "peach"}" },
  { name = "bzl", text = "", fg = "${theme.hex "green"}" },
  { name = "cljc", text = "", fg = "${theme.hex "green"}" },
  { name = "kicad_dru", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "fctl", text = "", fg = "${theme.hex "red"}" },
  { name = "f#", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "odt", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "conda", text = "", fg = "${theme.hex "green"}" },
  { name = "vala", text = "", fg = "${theme.hex "surface2"}" },
  { name = "erb", text = "", fg = "${theme.hex "crust"}" },
  { name = "mp3", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "bz2", text = "", fg = "${theme.hex "yellow"}" },
  { name = "coffee", text = "", fg = "${theme.hex "yellow"}" },
  { name = "cr", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "f90", text = "󱈚", fg = "${theme.hex "surface2"}" },
  { name = "jwmrc", text = "", fg = "${theme.hex "overlay0"}" },
  { name = "c++", text = "", fg = "${theme.hex "red"}" },
  { name = "fcscript", text = "", fg = "${theme.hex "red"}" },
  { name = "fods", text = "", fg = "${theme.hex "green"}" },
  { name = "cue", text = "󰲹", fg = "${theme.hex "red"}" },
  { name = "srt", text = "󰨖", fg = "${theme.hex "yellow"}" },
  { name = "info", text = "", fg = "${theme.hex "yellow"}" },
  { name = "hh", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "sig", text = "λ", fg = "${theme.hex "peach"}" },
  { name = "html", text = "", fg = "${theme.hex "peach"}" },
  { name = "iges", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "kicad_wks", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "hbs", text = "", fg = "${theme.hex "peach"}" },
  { name = "fcstd", text = "", fg = "${theme.hex "red"}" },
  { name = "gresource", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "sub", text = "󰨖", fg = "${theme.hex "yellow"}" },
  { name = "ical", text = "", fg = "${theme.hex "surface0"}" },
  { name = "crdownload", text = "", fg = "${theme.hex "teal"}" },
  { name = "pub", text = "󰷖", fg = "${theme.hex "yellow"}" },
  { name = "vue", text = "", fg = "${theme.hex "green"}" },
  { name = "gd", text = "", fg = "${theme.hex "overlay1"}" },
  { name = "fsx", text = "", fg = "${theme.hex "sapphire"}" },
  { name = "mkv", text = "", fg = "${theme.hex "peach"}" },
  { name = "py", text = "", fg = "${theme.hex "yellow"}" },
  { name = "kicad_sch", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "epub", text = "", fg = "${theme.hex "peach"}" },
  { name = "env", text = "", fg = "${theme.hex "yellow"}" },
  { name = "magnet", text = "", fg = "${theme.hex "surface1"}" },
  { name = "elf", text = "", fg = "${theme.hex "surface1"}" },
  { name = "fodg", text = "", fg = "${theme.hex "yellow"}" },
  { name = "svg", text = "󰜡", fg = "${theme.hex "peach"}" },
  { name = "dwg", text = "󰻫", fg = "${theme.hex "green"}" },
  { name = "docx", text = "󰈬", fg = "${theme.hex "surface2"}" },
  { name = "pro", text = "", fg = "${theme.hex "yellow"}" },
  { name = "db", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "rb", text = "", fg = "${theme.hex "crust"}" },
  { name = "r", text = "󰟔", fg = "${theme.hex "surface2"}" },
  { name = "scss", text = "", fg = "${theme.hex "red"}" },
  { name = "cow", text = "󰆚", fg = "${theme.hex "peach"}" },
  { name = "gleam", text = "", fg = "${theme.hex "pink"}" },
  { name = "v", text = "󰍛", fg = "${theme.hex "green"}" },
  { name = "kicad_pro", text = "", fg = "${theme.hex "rosewater"}" },
  { name = "liquid", text = "", fg = "${theme.hex "green"}" },
  { name = "zip", text = "", fg = "${theme.hex "yellow"}" },
]
  ''
