-- Keep which-key instant, but leave enough timeout for builtin-prefix mappings
-- like `m` to resolve to longer custom bindings instead of the builtin command.
vim.o.timeoutlen = 300

-- Load and configure which-key.nvim
local wk = require("which-key")

wk.setup({
  preset = "helix",
  delay = 0,
  sort = { "manual", "local", "group", "alphanum", "mod" },
  plugins = {
    registers = false,
    presets = {
      operators = true,
      motions = true,
      text_objects = true,
      windows = true,
      nav = true,
      z = true,
      g = false,
    },
  },
  triggers = {
    { "<auto>", mode = "nixsotc" },
    { "[", mode = "n" },
    { "]", mode = "n" },
    { "g", mode = "n" },
    { "m", mode = "n" },
    { '"', mode = "n" },
  },
  win = {
    no_overlap = false,
  },
})

wk.add({
  { "]", group = "Right bracket", mode = "n" },
  { "]d", desc = "Goto next diagnostic", mode = "n" },
  { "]D", desc = "Goto last diagnostic", mode = "n" },
  { "]g", desc = "Goto next change", mode = "n" },
  { "]G", desc = "Goto last change", mode = "n" },
  { "]f", desc = "Goto next function", mode = "n" },
  { "]t", desc = "Goto next type definition", mode = "n" },
  { "]a", desc = "Goto next parameter", mode = "n" },
  { "]c", desc = "Goto next comment", mode = "n" },
  { "]e", desc = "Goto next pairing", mode = "n" },
  { "]p", desc = "Goto next paragraph", mode = "n" },
  { "]x", desc = "Goto next (X)HTML element", mode = "n" },
  { "]<Space>", desc = "Add newline below", mode = "n" },
  { "]A", hidden = true, mode = "n" },
  { "]b", hidden = true, mode = "n" },
  { "]B", hidden = true, mode = "n" },
  { "]l", hidden = true, mode = "n" },
  { "]L", hidden = true, mode = "n" },
  { "]q", hidden = true, mode = "n" },
  { "]Q", hidden = true, mode = "n" },
  { "]T", hidden = true, mode = "n" },
  { "]%", hidden = true, mode = "n" },
  { "](", hidden = true, mode = "n" },
  { "]<", hidden = true, mode = "n" },
  { "]M", hidden = true, mode = "n" },
  { "]m", hidden = true, mode = "n" },
  { "]s", hidden = true, mode = "n" },
  { "]{", hidden = true, mode = "n" },
  { "]<C-L>", hidden = true, mode = "n" },
  { "]<C-Q>", hidden = true, mode = "n" },
  { "]<C-T>", hidden = true, mode = "n" },
  { "[", group = "Left bracket", mode = "n" },
  { "[d", desc = "Goto previous diagnostic", mode = "n" },
  { "[D", desc = "Goto first diagnostic", mode = "n" },
  { "[g", desc = "Goto previous change", mode = "n" },
  { "[G", desc = "Goto first change", mode = "n" },
  { "[f", desc = "Goto previous function", mode = "n" },
  { "[t", desc = "Goto previous type definition", mode = "n" },
  { "[a", desc = "Goto previous parameter", mode = "n" },
  { "[c", desc = "Goto previous comment", mode = "n" },
  { "[e", desc = "Goto previous pairing", mode = "n" },
  { "[p", desc = "Goto previous paragraph", mode = "n" },
  { "[x", desc = "Goto previous (X)HTML element", mode = "n" },
  { "[<Space>", desc = "Add newline above", mode = "n" },
  { "[A", hidden = true, mode = "n" },
  { "[b", hidden = true, mode = "n" },
  { "[B", hidden = true, mode = "n" },
  { "[l", hidden = true, mode = "n" },
  { "[L", hidden = true, mode = "n" },
  { "[q", hidden = true, mode = "n" },
  { "[Q", hidden = true, mode = "n" },
  { "[T", hidden = true, mode = "n" },
  { "[%", hidden = true, mode = "n" },
  { "[(", hidden = true, mode = "n" },
  { "[<", hidden = true, mode = "n" },
  { "[M", hidden = true, mode = "n" },
  { "[m", hidden = true, mode = "n" },
  { "[s", hidden = true, mode = "n" },
  { "[{", hidden = true, mode = "n" },
  { "[<C-L>", hidden = true, mode = "n" },
  { "[<C-Q>", hidden = true, mode = "n" },
  { "[<C-T>", hidden = true, mode = "n" },
  { "g", group = "Goto", mode = "n" },
  { "gg", desc = "Goto line number <n> else file start", mode = "n" },
  { "g|", desc = "Goto column", mode = "n" },
  { "ge", desc = "Goto last line", mode = "n" },
  { "gf", desc = "Goto files/URLs in selections", mode = "n" },
  { "gh", desc = "Goto line start", mode = "n" },
  { "gl", desc = "Goto line end", mode = "n" },
  { "gs", desc = "Goto first non-blank in line", mode = "n" },
  { "gd", desc = "Goto definition", mode = "n" },
  { "gD", desc = "Goto declaration", mode = "n" },
  { "gy", desc = "Goto type definition", mode = "n" },
  { "gr", desc = "Goto references", mode = "n" },
  { "gi", desc = "Goto implementation", mode = "n" },
  { "gt", desc = "Goto window top", mode = "n" },
  { "gc", desc = "Goto window center", mode = "n" },
  { "gb", desc = "Goto window bottom", mode = "n" },
  { "ga", desc = "Goto last accessed file", mode = "n" },
  { "gm", desc = "Goto last modified file", mode = "n" },
  { "gn", desc = "Goto next buffer", mode = "n" },
  { "gp", desc = "Goto previous buffer", mode = "n" },
  { "gk", desc = "Show docs for item under cursor in a buffer", mode = "n" },
  { "gj", desc = "Move down", mode = "n" },
  { "g.", desc = "Goto last modification", mode = "n" },
  { "gq", desc = "Close the current buffer.", mode = "n" },
  { "gQ", desc = "Close the current buffer forcefully, ignoring unsaved changes.", mode = "n" },
  { "g`", hidden = true, mode = "n" },
  { "g'", hidden = true, mode = "n" },
  { "gu", hidden = true, mode = "n" },
  { "gU", hidden = true, mode = "n" },
  { "g~", hidden = true, mode = "n" },
  { "gw", hidden = true, mode = "n" },
  { "gO", hidden = true, mode = "n" },
  { "gcc", hidden = true, mode = "n" },
  { "gR", hidden = true, mode = "n" },
  { "gx", hidden = true, mode = "n" },
  { "g%", hidden = true, mode = "n" },
  { "m", group = "Match", mode = "n" },
  { "ma", group = "Match around", mode = "n" },
  { "maw", desc = "Word", mode = "n" },
  { "maW", desc = "WORD", mode = "n" },
  { "map", desc = "Paragraph", mode = "n" },
  { "mai", desc = "Indentation level", mode = "n" },
  { "mat", desc = "Type definition (tree-sitter)", mode = "n" },
  { "maf", desc = "Function (tree-sitter)", mode = "n" },
  { "maa", desc = "Argument/parameter (tree-sitter)", mode = "n" },
  { "mac", desc = "Comment (tree-sitter)", mode = "n" },
  { "mae", desc = "Data structure entry (tree-sitter)", mode = "n" },
  { "mam", desc = "Closest surrounding pair (tree-sitter)", mode = "n" },
  { "mag", desc = "Change", mode = "n" },
  { "max", desc = "(X)HTML element (tree-sitter)", mode = "n" },
  { "mi", group = "Match inside", mode = "n" },
  { "miw", desc = "Word", mode = "n" },
  { "miW", desc = "WORD", mode = "n" },
  { "mip", desc = "Paragraph", mode = "n" },
  { "mii", desc = "Indentation level", mode = "n" },
  { "mit", desc = "Type definition (tree-sitter)", mode = "n" },
  { "mif", desc = "Function (tree-sitter)", mode = "n" },
  { "mia", desc = "Argument/parameter (tree-sitter)", mode = "n" },
  { "mic", desc = "Comment (tree-sitter)", mode = "n" },
  { "mie", desc = "Data structure entry (tree-sitter)", mode = "n" },
  { "mim", desc = "Closest surrounding pair (tree-sitter)", mode = "n" },
  { "mig", desc = "Change", mode = "n" },
  { "mix", desc = "(X)HTML element (tree-sitter)", mode = "n" },
  { "mdm", desc = "Nearest matching pair", mode = "n" },
  { "<leader>", group = "Space", mode = "n" },
  { "<leader>f", desc = "Open file picker", mode = "n" },
  { "<leader>F", desc = "Open file picker at current working directory", mode = "n" },
  { "<leader>e", desc = "Open file explorer in workspace root", mode = "n" },
  { "<leader>E", desc = "Open file explorer at current buffer's directory", mode = "n" },
  { "<leader>b", desc = "Open buffer picker", mode = "n" },
  { "<leader>j", desc = "Open jumplist picker", mode = "n" },
  { "<leader>s", desc = "Open symbol picker from LSP or syntax information", mode = "n" },
  { "<leader>S", desc = "Open workspace symbol picker from LSP or syntax information", mode = "n" },
  { "<leader>d", desc = "Open diagnostic picker", mode = "n" },
  { "<leader>D", desc = "Open workspace diagnostic picker", mode = "n" },
  { "<leader>a", desc = "Perform code action", mode = "n" },
  { "<leader>'", desc = "Open last picker", mode = "n" },
  { "<leader>w", group = "Window", mode = "n" },
  { "<leader>y", desc = "Yank selections to clipboard", mode = "n" },
  { "<leader>Y", desc = "Yank main selection to clipboard", mode = "n" },
  { "<leader>p", desc = "Paste clipboard after selections", mode = "n" },
  { "<leader>P", desc = "Paste clipboard before selections", mode = "n" },
  { "<leader>R", desc = "Replace selections by clipboard content", mode = "n" },
  { "<leader>/", desc = "Global search in workspace folder", mode = "n" },
  { "<leader>k", desc = "Show docs for item under cursor", mode = "n" },
  { "<leader>r", desc = "Rename symbol", mode = "n" },
  { "<leader>h", desc = "Select symbol references", mode = "n" },
})
