/*
  Legion hardware profile notes
  =============================

  This file is the hand-written hardware / graphics policy layer for the host
  named `legion`.

  The goal of this comment block is to capture the important machine facts that
  were discovered while auditing and rewriting the old driver configuration, so
  future edits do not need to start from zero.

  Machine identity
  ----------------
  - Vendor: LENOVO
  - DMI product code: 82RF
  - Mainboard: LNVNB161216
  - BIOS version seen during audit: J2CN57WW
  - Closest upstream nixos-hardware match: `lenovo-legion-16iah7h`
  - Practical interpretation: this is a Lenovo Legion hybrid Intel + NVIDIA laptop
    in the 16IAH7H family, so importing the upstream Legion 16IAH7H module makes
    sense and avoids carrying a pile of custom laptop quirks by hand.

  CPU / memory
  ------------
  - CPU: 12th Gen Intel Core i7-12700H
  - Topology reported during audit: 20 logical CPUs, 14 cores, 1 socket
  - Virtualization support reported by `lscpu`: VT-x
  - RAM seen during audit: about 32 GiB (`MemTotal: 32651420 kB`)

  Graphics hardware
  -----------------
  - Integrated GPU path: Intel Alder Lake iGPU using the `i915` kernel driver
  - Dedicated GPU: NVIDIA GA104M / GeForce RTX 3070 Ti Laptop GPU
  - NVIDIA audio function also present at PCI device `01:00.1`
  - Hybrid graphics layout: Intel iGPU + NVIDIA dGPU
  - Intel bus ID: `PCI:00:02:0`
  - NVIDIA bus ID: `PCI:01:00:0`

  Display information observed in the live Hyprland session
  ---------------------------------------------------------
  - Internal panel connector: `eDP-1`
  - Panel vendor string reported by Hyprland: `BOE 0x0A1F`
  - Native resolution observed: 2560x1600
  - Available refresh rates observed: 60 Hz and 165 Hz
  - Hyprland scale observed during audit: 1.60

  Software / kernel context during the audit
  ------------------------------------------
  - OS version seen live: NixOS 26.05 pre-release (`26.05.20260318.b40629e`)
  - Kernel seen live: `6.18.13-zen1`
  - NVIDIA driver seen live: `580.142`

  What we actually observed on this machine
  -----------------------------------------
  - Firmware `dGPU-only` mode was able to boot Hyprland and use the NVIDIA GPU.
  - Firmware `hybrid` mode was able to boot Hyprland on the Intel GPU.
  - Firmware `hybrid` mode did *not* yield a healthy NVIDIA offload path.
  - We tried the following NVIDIA combinations in hybrid mode:
    - open kernel modules
    - proprietary kernel modules
    - proprietary kernel modules with GSP explicitly disabled
  - In all of those hybrid-mode attempts, the NVIDIA dGPU still failed adapter
    initialization with errors such as:
    - `RmInitAdapter failed`
    - `Failed to allocate NvKmsKapiDevice`
    - `nvidia-smi: No devices were found`

  Current policy encoded by this file
  ----------------------------------
  - Default boot behavior is now `Intel-only`.
  - This default is intended for the machine when firmware is in `hybrid` mode.
  - The normal desktop, browsers, and CPU-heavy work should run on Intel.
  - A specialisation named `nvidia-only` exists for when the machine is switched to
    firmware `dGPU-only` mode and you intentionally want NVIDIA to be the only GPU.
  - We do *not* currently treat hybrid PRIME offload as a supported / trusted mode
    on this Legion, because repeated real-world testing on this exact machine did
    not produce a healthy NVIDIA dGPU in hybrid mode.
  - Both supported modes were later re-tested successfully:
    - default boot + firmware hybrid mode produced a healthy Intel-only session
    - `nvidia-only` boot + firmware dGPU-only mode produced a healthy NVIDIA-only
      session with working `nvidia-smi` and Hyprland rendering on the dGPU.

  Practical recommendation based on the evidence so far
  -----------------------------------------------------
  - Use the default boot for normal laptop use, battery-sensitive work, and CPU-
    heavy tasks such as compiling large projects.
  - Use the `nvidia-only` specialisation only when you intentionally want the
    machine to run in firmware `dGPU-only` mode for gaming, CUDA, rendering, or
    other workloads that truly need a working NVIDIA device.
  - In the `nvidia-only` mode, the internal panel was observed defaulting to 60 Hz
    despite 165 Hz being available, so the Home Manager Hyprland config now pins
    the Legion internal display to `2560x1600@165` explicitly.
  - The Legion host now also installs the `lenovo-legion` userspace tool and a
    helper wrapper named `legion-gpu-mode` to make switching firmware GPU mode and
    pairing it with the matching next GRUB entry less error-prone.

  Things intentionally *not* encoded here
  ---------------------------------------
  - `hardware-configuration.nix` remains the autogenerated source of truth for
    disks, swap, and installer-detected hardware.
  - We no longer try to encode hybrid PRIME offload as the intended mode, because
    doing so would describe a mode that did not hold up on the real hardware.
  - If a future kernel / NVIDIA / firmware combination finally makes hybrid NVIDIA
    reliable on this Legion, the audit docs in this host folder should be updated
    before reintroducing that policy here.
*/

# Sources used while rewriting this file
# -------------------------------------
# Upstream machine profile:
# - https://github.com/NixOS/nixos-hardware/blob/master/lenovo/legion/16iah7h/default.nix
#
# Upstream PRIME helper module:
# - https://github.com/NixOS/nixos-hardware/blob/master/common/gpu/nvidia/prime.nix
#
# Upstream Intel GPU module used by nixos-hardware:
# - https://github.com/NixOS/nixos-hardware/blob/master/common/gpu/intel/default.nix
#
# Upstream NixOS NVIDIA module implementation:
# - https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/hardware/video/nvidia.nix
#
# NVIDIA documentation consulted while testing GSP-related behavior:
# - https://download.nvidia.com/XFree86/Linux-x86_64/580.95.05/README/gsp.html
#
# Legion firmware control project used for mode-switch integration:
# - https://github.com/johnfanv2/LenovoLegionLinux
#
# Reference documentation consulted during the audit:
# - https://wiki.nixos.org/wiki/NVIDIA
# - https://wiki.nixos.org/wiki/Accelerated_Video_Playback
# - https://wiki.hypr.land/Nvidia/
#
# Live machine facts in the header above were gathered directly from this host via:
# - `lscpu`
# - `lspci -nn` / `lspci -nnk`
# - `nvidia-smi`
# - `hyprctl -j monitors`
# - `/sys/devices/virtual/dmi/id/*`
# - `/proc/meminfo`
# - `/proc/cmdline`
# - `journalctl -b`

{ lib, config, pkgs, inputs, ... }:

let
  legionGpuMode = pkgs.writeShellScriptBin "legion-gpu-mode" ''
    #!/usr/bin/env bash
    set -euo pipefail

    usage() {
      cat <<'EOF'
Usage: legion-gpu-mode <status|hybrid|nvidia>

Commands:
  status   Show observed firmware mode, current boot profile, and raw Legion tool status
  hybrid   Switch firmware to hybrid mode, set the next GRUB boot to the default profile, then reboot
  nvidia   Switch firmware to dGPU-only mode, set the next GRUB boot to the nvidia-only profile, then reboot
EOF
    }

    observed_mode() {
      local display
      display="$(${pkgs.pciutils}/bin/lspci -D -d ::03xx 2>/dev/null || true)"

      if printf '%s\n' "$display" | ${pkgs.gnugrep}/bin/grep -q '0000:00:02.0' \
        && printf '%s\n' "$display" | ${pkgs.gnugrep}/bin/grep -q '0000:01:00.0'; then
        printf 'hybrid\n'
      elif printf '%s\n' "$display" | ${pkgs.gnugrep}/bin/grep -q '0000:01:00.0' \
        && ! printf '%s\n' "$display" | ${pkgs.gnugrep}/bin/grep -q '0000:00:02.0'; then
        printf 'nvidia\n'
      else
        printf 'unknown\n'
      fi
    }

    current_boot_profile() {
      if ${pkgs.gnugrep}/bin/grep -q 'nixos-system-legion-nvidia-only-' /proc/cmdline; then
        printf 'nvidia-only\n'
      else
        printf 'default\n'
      fi
    }

    latest_grub_entry() {
      local selector="$1"
      local cfg=/boot/grub/grub.cfg

      if [[ ! -r "$cfg" ]]; then
        printf 'Could not read %s\n' "$cfg" >&2
        exit 1
      fi

      case "$selector" in
        default)
          ${pkgs.gawk}/bin/awk -F'"' '/^menuentry "NixOS - .*Default/ { print $2; exit }' "$cfg"
          ;;
        nvidia)
          ${pkgs.gawk}/bin/awk -F'"' '/^menuentry "NixOS - .*nvidia-only/ { print $2; exit }' "$cfg"
          ;;
        *)
          printf 'Unknown selector: %s\n' "$selector" >&2
          exit 1
          ;;
      esac
    }

    require_root() {
      if [[ ''${EUID:-$(id -u)} -ne 0 ]]; then
        exec ${pkgs.sudo}/bin/sudo "$0" "$@"
      fi
    }

    raw_legion_status() {
      local raw
      raw="$(${pkgs.lenovo-legion}/bin/legion_cli hybrid-mode-status 2>&1 || true)"

      if [[ -z "$raw" ]]; then
        return 0
      fi

      while IFS= read -r line; do
        case "$line" in
          True)
            printf '%s\n' 'True  (hybrid mode enabled in firmware)'
            ;;
          False)
            printf '%s\n' 'False (hybrid mode disabled in firmware; dGPU-only mode)'
            ;;
          *)
            printf '%s\n' "$line"
            ;;
        esac
      done <<< "$raw"
    }

    cmd="''${1:-}"

    case "$cmd" in
      status)
        printf 'Observed firmware mode: %s\n' "$(observed_mode)"
        printf 'Current boot profile:   %s\n' "$(current_boot_profile)"
        printf '\nRaw LenovoLegionLinux status output:\n'
        raw_legion_status
        ;;

      hybrid)
        require_root "$@"
        entry="$(latest_grub_entry default)"
        if [[ -z "$entry" ]]; then
          printf 'Could not find a default GRUB entry to boot next.\n' >&2
          exit 1
        fi
        ${pkgs.lenovo-legion}/bin/legion_cli hybrid-mode-enable
        ${pkgs.grub2}/bin/grub-reboot "$entry"
        printf 'Set firmware target to hybrid mode.\n'
        printf 'Set next GRUB boot entry to: %s\n' "$entry"
        printf 'Rebooting now...\n'
        ${pkgs.systemd}/bin/systemctl reboot
        ;;

      nvidia)
        require_root "$@"
        entry="$(latest_grub_entry nvidia)"
        if [[ -z "$entry" ]]; then
          printf 'Could not find a nvidia-only GRUB entry to boot next.\n' >&2
          exit 1
        fi
        ${pkgs.lenovo-legion}/bin/legion_cli hybrid-mode-disable
        ${pkgs.grub2}/bin/grub-reboot "$entry"
        printf 'Set firmware target to dGPU-only mode.\n'
        printf 'Set next GRUB boot entry to: %s\n' "$entry"
        printf 'Rebooting now...\n'
        ${pkgs.systemd}/bin/systemctl reboot
        ;;

      -h|--help|help|"")
        usage
        ;;

      *)
        printf 'Unknown command: %s\n\n' "$cmd" >&2
        usage >&2
        exit 1
        ;;
    esac
  '';
in
{
  imports = [
    # Use the upstream hardware profile for this Legion family.
    #
    # This module already knows about the Intel + NVIDIA laptop layout for this
    # chassis and brings in the common laptop, SSD, Intel CPU/iGPU, NVIDIA Ampere,
    # PRIME, and HiDPI defaults that make sense for this machine.
    #
    # In practice, this means we do not have to hand-maintain every laptop quirk in
    # this file. Instead, this file can stay focused on the graphics policy choices
    # we actually trust on this specific machine.
    inputs.nixos-hardware.nixosModules.lenovo-legion-16iah7h
  ];

  # Keep using the Zen kernel on this host.
  #
  # This is not strictly required for the graphics policy itself, but it is a host-
  # level kernel choice that your Legion has already been using successfully.
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_zen;

  hardware.graphics = {
    # Enable the system graphics stack.
    #
    # This turns on the OpenGL / Vulkan userspace path and is the base requirement
    # for both the Intel iGPU and the NVIDIA dGPU, regardless of which one is
    # actually chosen at runtime.
    enable = true;

    # Keep 32-bit graphics support enabled.
    #
    # This matters for older games, Wine / Proton, and any other 32-bit graphics
    # applications you may want to run on this laptop.
    enable32Bit = true;
  };

  hardware.intelgpu = {
    # Alder Lake laptops still use the classic Intel `i915` kernel driver.
    #
    # This is the integrated GPU path the laptop uses for its stable, low-power,
    # everyday desktop mode when firmware is set to hybrid.
    driver = "i915";

    # Load the Intel GPU driver in the initrd.
    #
    # On this laptop the internal display path is healthy through Intel, so loading
    # the iGPU driver early is a sensible default.
    loadInInitrd = true;

    # Use the modern compute runtime for Gen12+ Intel graphics.
    computeRuntime = "default";

    # Use the newer Intel media runtime rather than the older Media SDK path.
    mediaRuntime = "vpl-gpu-rt";

    # Prefer the modern VA-API driver for Alder Lake.
    #
    # This keeps browser and video decode work on the Intel side, which is exactly
    # what we want in the default Intel-only operating mode.
    vaapiDriver = "intel-media-driver";

    # Keep hybrid codec support enabled.
    #
    # This preserves the intent from the earlier hand-tuned config without relying
    # on a global package override.
    enableHybridCodec = true;
  };

  environment.sessionVariables = {
    # Ask VA-API clients to use the Intel media driver by default.
    #
    # This matches the host's new default operating model: Intel-first, everyday
    # laptop mode, with NVIDIA reserved for a separate explicit specialisation.
    LIBVA_DRIVER_NAME = "iHD";
  };

  environment.systemPackages = [
    # Legion-specific firmware / platform control utility.
    #
    # This is the Linux-side replacement for some of the machine controls Lenovo
    # normally exposes through Windows software such as Lenovo Vantage.
    pkgs.lenovo-legion

    # Host-local helper that pairs firmware GPU-mode switching with the correct next
    # GRUB boot entry so you are less likely to reboot into the wrong profile.
    legionGpuMode
  ];

  services.xserver.videoDrivers = [
    # Default this host to the generic modesetting driver.
    #
    # In practical terms, this is our "Intel-only" policy choice. We do *not* want
    # the default boot to ask NixOS to bring up the NVIDIA stack, because that path
    # repeatedly failed in hybrid mode on the real hardware.
    "modesetting"
  ];

  boot.blacklistedKernelModules = [
    # Keep nouveau disabled in all modes.
    #
    # We do not want the third-party open-source Nouveau driver racing the NVIDIA
    # stack in the specialisation that intentionally enables NVIDIA.
    "nouveau"

    # Default mode is Intel-only, so block the NVIDIA modules from loading.
    #
    # This is the cleanest way to make the default boot stop trying to create a
    # half-broken hybrid NVIDIA setup.
    "nvidia"
    "nvidia_drm"
    "nvidia_modeset"
    "nvidia_uvm"
    "nvidiafb"
  ];

  hardware.nvidia = {
    # Keep the NVIDIA package choice documented globally.
    #
    # The specialisation below inherits from this unless it overrides a field.
    package = config.boot.kernelPackages.nvidiaPackages.production;

    # Record the NVIDIA module preference we would use if the stack is enabled.
    #
    # The default Intel-only boot blacklists the NVIDIA modules anyway, so this only
    # really matters in the `nvidia-only` specialisation.
    #
    # We keep the base value conservative here because the default boot should not
    # actually be using NVIDIA at all.
    open = false;

    # Keep the standard Wayland-capable NVIDIA setting documented.
    modesetting.enable = true;

    # Install `nvidia-settings` for the mode where NVIDIA is intentionally enabled.
    nvidiaSettings = true;

    # Keep NVIDIA's suspend / resume integration available when the specialisation
    # intentionally enables the dGPU.
    powerManagement.enable = true;

    # Do not use the hybrid offload-specific runtime PM path by default.
    #
    # Fine-grained power management only makes sense for a healthy PRIME offload
    # setup, and that is *not* the operating model we trust on this host anymore.
    powerManagement.finegrained = lib.mkForce false;

    # Leave Dynamic Boost disabled.
    #
    # It previously caused noisy `nvidia-powerd` behavior and has not earned its way
    # back into the configuration.
    dynamicBoost.enable = false;

    prime = {
      offload = {
        # Explicitly disable PRIME offload.
        #
        # This is the heart of the policy change in this file. We are no longer
        # presenting hybrid NVIDIA offload as a supported mode on this machine.
        enable = lib.mkForce false;

        # No offload helper is needed when offload itself is intentionally disabled.
        enableOffloadCmd = lib.mkForce false;
      };

      # Keep the real bus IDs documented.
      #
      # Even though we are not currently trusting PRIME offload, these identifiers
      # are still true facts about the hardware and are worth preserving here.
      intelBusId = "PCI:00:02:0";
      nvidiaBusId = "PCI:01:00:0";
    };
  };

  specialisation = {
    nvidia-only.configuration = {
      system.nixos.tags = [ "nvidia-only" ];

      services.xserver.videoDrivers = lib.mkForce [
        # This specialisation is the deliberate "NVIDIA-only" boot path.
        #
        # Use it when the laptop firmware has been switched to dGPU-only mode and
        # you intentionally want the system to run on NVIDIA for gaming, CUDA,
        # rendering, or other workloads that genuinely need the dGPU.
        "nvidia"
      ];

      boot.blacklistedKernelModules = lib.mkForce [
        # Nouveau still stays blacklisted here.
        #
        # In the NVIDIA-only specialisation we want the real NVIDIA stack, not the
        # fallback open-source Nouveau driver.
        "nouveau"
      ];

      environment.sessionVariables = {
        # Tell VA-API clients to use the NVIDIA VA-API path in the mode where the
        # NVIDIA GPU is intentionally the only active graphics device.
        LIBVA_DRIVER_NAME = lib.mkForce "nvidia";

        # Recommended by the Hyprland NVIDIA documentation for the third-party
        # `nvidia-vaapi-driver` userspace path.
        NVD_BACKEND = lib.mkForce "direct";
      };

      hardware.nvidia = {
        # This specialisation intentionally returns to the NVIDIA open kernel module
        # path, because that is the combination we actually observed working when the
        # machine firmware was previously forced into dGPU-only mode.
        #
        # We do *not* infer from that that hybrid open-mode is healthy. It was not.
        # This choice is only for the explicitly separate NVIDIA-only operating mode,
        # and it has now also been re-validated successfully after the two-mode
        # redesign.
        open = lib.mkForce true;

        # Fine-grained runtime PM is a hybrid-offload concern, so keep it disabled in
        # the NVIDIA-only mode where the dGPU is the intentional primary device.
        powerManagement.finegrained = lib.mkForce false;

        prime.offload.enable = lib.mkForce false;
        prime.offload.enableOffloadCmd = lib.mkForce false;
        prime.sync.enable = lib.mkForce false;
      };
    };
  };

  # Intentionally omitted from the old file:
  #
  # - `services.fstrim.enable`
  #   The imported nixos-hardware Legion module already pulls in the common SSD
  #   module, which sets this for us.
  #
  # - `hardware.nvidia-container-toolkit.enable`
  #   Your evaluated config does not currently enable Docker on this host, so this
  #   would just be unused complexity.
  #
  # - Repeated hybrid NVIDIA workaround churn
  #   We tried multiple real NVIDIA configurations in hybrid mode and the dGPU still
  #   failed adapter initialization on this machine. Rather than keep piling on more
  #   folklore workarounds, the file now encodes two modes we can actually explain:
  #   Intel-only by default, and NVIDIA-only by explicit specialisation.
}
