theme = "tokyonight"

[editor]
scrolloff = 8
auto-pairs = false
insert-final-newline = false
mouse = false
color-modes = true
bufferline = "always"
line-number = "relative"
popup-border = "all"
shell = ["nu", "-c"]
idle-timeout = 0

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-progress-messages = true

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"

[keys]
[keys.insert]
"C-space" = "completion"
"C-o" = "normal_mode"

[keys.normal]
# Buffer binds
H = "goto_previous_buffer" # Move to left buffer
L = "goto_next_buffer"     # Move to right buffer
g.q = ":bc"  # Close buffer
g.Q = ":bc!" # Close buffer with unsaved changed 

# Lazygit integration
C-g = [
    ":write-all",
    ":insert-output lazygit out> /dev/tty",
    ":redraw",
    ":reload-all"
]

# Scooter integration
C-r = [
    ":write-all",
    ":insert-output scooter out> /dev/tty",
    ":redraw",
    ":reload-all"
]

# Yazi integration
- = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

# Remaps
x = "extend_line" # Now extends based off where head is 
 
[keys.select]
# Remaps
x = "extend_line" # Now extends based off where head is 
