theme = "tokyonight"

[editor]
auto-pairs = false
mouse = false
color-modes = true
bufferline = "always"
line-number = "relative"
shell = ["fish", "-c"]
idle-timeout = 0

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys]
[keys.insert]
"C-space" = "completion"

[keys.normal]
H = "goto_previous_buffer" # Move to left buffer
L = "goto_next_buffer"     # Move to right buffer
g.q = ":bc"  # Close buffer
g.Q = ":bc!" # Close buffer with unsaved changed 
