theme = "tokyonight"

[editor]
scrolloff = 8
auto-pairs = false
insert-final-newline = false
mouse = false
color-modes = true
bufferline = "always"
line-number = "relative"
popup-border = "all"
shell = ["fish", "-c"]
idle-timeout = 0

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-progress-messages = true

[keys]
[keys.insert]
"C-space" = "completion"

[keys.normal]
# Buffer binds
H = "goto_previous_buffer" # Move to left buffer
L = "goto_next_buffer"     # Move to right buffer
g.q = ":bc"  # Close buffer
g.Q = ":bc!" # Close buffer with unsaved changed 

# Lazygit integration
C-g = [
    ":write-all",
    ":insert-output lazygit >/dev/tty",
    ":redraw",
    ":reload-all"
]

# Scooter integration
C-r = [
    ":write-all",
    ":insert-output scooter >/dev/tty",
    ":redraw",
    ":reload-all"
]

# Yazi integration (FIXME: Broken, should be fixed in next Helix update)
- = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

# Remaps
x = "extend_line" # Now extends based off where head is 
 
[keys.select]
# Remaps
x = "extend_line" # Now extends based off where head is 
