[[language]]
auto-format = false
name = "cpp"

[language.indent]
tab-width = 4
unit = "    "

[[language]]
name = "latex"

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true
# configure tectonic as the build tool
executable = "tectonic"
args = ["-X", "compile", "%f", "--synctex", "-Zshell-escape", "--keep-logs", "--keep-intermediates"]

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:1:%f", "%p" ]

[language-server.texlab.config.texlab.chktex]
onEdit = true

[[language]]
name = "python"

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true
