name = "gleetcode"
version = "1.0.0"
description = "A small, auditable Gleam LeetCode CLI"
licences = ["MIT"]
target = "erlang"
internal_modules = ["gleetcode/internal", "gleetcode/internal/*"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.0 and < 2.0.0"
envoy = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
