#!/bin/sh

server=$1
progpath=$2
kind=$3
repo=$4
number=$5

if [ -z "$server" ] || [ -z "$progpath" ] || [ -z "$kind" ] || [ -z "$repo" ] || [ -z "$number" ]; then
  exit 1
fi

case "$kind" in
  issue|pr) ;;
  *) exit 1 ;;
esac

case "$number" in
  ''|*[!0-9]*) exit 1 ;;
esac

exec "$progpath" --server "$server" --remote-send "<Cmd>lua require('axelcool1234.gh_dash').open_target('$kind','$repo',$number)<CR>"
